version: "3.9"
services:
  app:
    tty: true
    image: ghcr.io/macedonsky777/py_dock_actions:tests
    build:
      context: .
      dockerfile: Dockerfile_tests

  app-coverage:
    container_name: app-coverage
    path: coverage/index.html
    tty: true
    image: ghcr.io/macedonsky777/py_dock_actions:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    entrypoint: bash -c "python3 -m coverage run -m unittest && python3 -m coverage html"
    volumes:
      - /coverage:/workdir/htmlcov

  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty1234
    ports:
      - 3306:3306
