name: Build

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: macedonsky777/py_dock_actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image with tests
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile_tests
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tests


    - name: Test coverage
      run: |
        mkdir coverage 
        docker-compose up app-coverage
        rm -rf coverage/.gitignore
    
    - name: push coverage
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Alex Macedonsky
        author_email: yano.motoharu.kikuchi@gmail.com
        message: 'Add code coverage report'
        add: 'coverage'
        pull: '-r'
        push: true
    
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: main
        build_dir: coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage/index.html
