name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: dockerize -wait tcp://localhost:3306 -timeout 1m

    - name: Run MySQL migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        coverage run py_dock_actions/tests/tests.py
        coverage report -m

    - name: EndBug/add-and-commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Alex Macedonsky'
        author_email: 'yano.motoharu.kikuchi@gmail.com'
        message: 'Add code coverage report'

    - name: crazy-max/ghaction-github-pages
      uses: crazy-max/ghaction-github-pages@v4

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov
