name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t pythonactionsdock . --file Dockerfile --tag my-image-name:$(date +%s)
