name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MySQL
      uses: mysql/setup-mysql@v2
      with:
        mysql-version: '8.0'
        password: ${{ secrets.DB_PASSWORD }}

    - name: Run MySQL migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        coverage run py_dock_actions/tests/tests.py
        coverage report -m

    - name: EndBug/add-and-commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Alex Macedonsky'
        author_email: 'yano.motoharu.kikuchi@gmail.com'
        message: 'Add code coverage report'

    - name: crazy-max/ghaction-github-pages
      uses: crazy-max/ghaction-github-pages@v4

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov
